<?php
$checkUseForShipping = Mage::getSingleton('core/session')->getData('use_for_shipping'); ?>
<script type="text/javascript">
countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?>
</script>
<div class="easycheout_main v-fix f-fix">
    <div class="easycheout_main_header">
        <h1><?php echo Mage::helper('easycheckout')->getEasycheckoutTitle(); ?></h1>
        <h2><?php echo Mage::helper('easycheckout')->getEasycheckoutContent() ?></h2>
        <?php if(!$this->isCustomerLoggedIn() && Mage::helper('easycheckout')->getEasycheckoutConfig('general/enable_login')): ?>
           
                    <?php echo $this->getChildHtml('osc-login'); ?>
              
        <?php endif; ?>
       
    </div>
    <div id="easycheckout-ajax-loader" style="display:none;">
        <div id="easycheckout-ajax-loader-text"> Loading...</div>
    </div>
    
    <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
        <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; ?>
        <?php if($_stepId == 'login'): ?>
            <div class="onestepcheckout-<?php echo $_stepId ?>">            
                <div class="checkout-step-<?php echo $_stepId ?>">
                    <?php echo $this->getChildHtml($_stepId) ?>
                </div>
            </div>
        <?php else: ?>
        <?php if($_stepId == 'shipping'): ?>
            <?php if($checkUseForShipping): ?>
                <?php $i++; ?>
            <?php endif; ?>
        <?php else: ?>
            <?php $i++ ?>
        <?php endif; ?>
        <?php if($_stepId == 'billing'): ?>
            <form id="onestepcheckout-form" action="" method="post">
                <div id="os-container" class="clearfix f-fix v-fix">
                    <div id="os-row">
                        <div id="os-left" class="f-left left">
                            <ol class="first">
        <?php endif; ?>
        <?php if($_stepId == 'shipping_method' || $i == 2): ?>
                            </ol>
                        </div >
                        <div id="os-right" class="f-left left">
                            <ol class="">
        <?php elseif($_stepId == 'review'):?>
                            </ol>
                            <div id="os-review" >
                                <ol class="">
        <?php endif;?>
        <?php if($_stepId == 'shipping'): ?>
                                    <li class="step <?php echo $_stepId ?>" <?php if($checkUseForShipping): ?>style="display:block;"<?php else: ?>style="display:none;"<?php endif; ?> id="shipping-address-form">
        <?php else: ?>
                                    <li class="<?php echo $_stepId ?> ">
        <?php endif; ?>
                                        <div class="easycheout_headings easycheckout-title"  <?php echo "style='". Mage::helper('easycheckout')->getEasycheckoutskin() . "'"; ?>>
                                            <span id="easycheckout-number" <?php if($_stepId == 'review'): ?>class="step-review"<?php elseif($checkUseForShipping): ?>class="step-<?php echo $i ?>"<?php elseif($_stepId != 'shipping'): ?>class="step-<?php echo $i ?>"<?php endif; ?>></span>
                                            <h3 <?php echo "style='". Mage::helper('easycheckout')->getEasycheckoutHeadingCSS() . "'"; ?>><?php echo $_stepInfo['label'] ?></h3>
                                        </div>
                                            <?php echo $this->getChildHtml($_stepId) ?>
                                    </li>
        <?php endif; ?>
    <?php endforeach ?>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="clear"></div>           
</div>
<script type="text/javascript">
//<![CDATA[
billing.cartupdateinit('<?php echo $this->getUrl('checkout/onestep/cartupdate') ?>');
    var addaddressb4review='<?php echo $this->getUrl('checkout/onestep/save_Before_Review') ?>';
    var easycheckout = new Easycheckout(
                {
                    failure: '<?php echo $this->getUrl('checkout/onepage/failure') ?>',
                    reloadReview: '<?php echo $this->getUrl('checkout/onestep/reloadReview') ?>',
                    reloadPayment: '<?php echo $this->getUrl('checkout/onestep/reloadPayment') ?>',
                    success: '<?php echo $this->getUrl('checkout/onepage/success') ?>'
                }                                      
            );
    if($('billing-address-select')) {
        billing.setAddress($('billing-address-select').value);
    } else {
        billing.saveCountry();
    }
    
          
function processOnepagecheckoutResponse(response) {
    processResponse (response);
easycheckout.setLoadWaitingReview('saving_order');
    if (response.get('ret_status') == 'SUCCESS') {
        if (response.get('paydata_bank_name'))
            document.getElementById('ipayment_elv_bank_name').value = response.get('paydata_bank_name');

        new Ajax.Request(
        	saveSessInfoUrlGlobal,
            {
                method:'post',
                parameters: Form.serialize(billing.form)
            }
        );
        
        var request = new Ajax.Request(
            billing.saveUrlpayment,
            {
                method:'post',
                onComplete:easycheckout.resetLoadWaitingReview.bind(easycheckout),
                onSuccess: billing.processIpayment.bind(easycheckout),
                onFailure: easycheckout.ajaxFailure.bind(false),
                parameters: Form.serialize(billing.form)
            }
        );
    }
}
//]]>
</script>
