 <?php $required=Mage::helper('easycheckout')->getEasycheckoutConfig('quickheared/enable_quickheared');?>
<p class="easycheckout-agreement-p">
    <label for="easycheckout_heared"><?php echo Mage::helper('easycheckout')->getEasycheckoutConfig('quickheared/label_quickheared'); ?></label>
    <select id="easycheckout_heared" name="easycheckout_heard" title="<?php echo $this->__(Mage::helper('easycheckout')->getEasycheckoutConfig('quickheared/label_quickheared')) ?>" class="<?php if($required=='1'){echo "validate-select";}?>" >
        <option value=""><?php echo $this->__('Please select an Option') ?></option>
        <?php
        if($sources=Mage::helper('easycheckout')->getEasycheckoutHeard()):
        foreach($sources as $_option): ?>
            <option value="<?php echo $_option ?>"><?php echo $_option ?></option>
        <?php endforeach;
            endif;
        ?>
        <option value="Others"><?php echo $this->__('Others'); ?></option>
    </select>
    <input id="easycheckout_other" type="text" class="<?php if($required=='1'){echo "required-entry";}?>" value="" name="easycheckout_other" style="display:none;">
</p>
<script type="text/javascript">
 //<![CDATA[
    $('easycheckout_heared').observe('change', function(event){
        if($('easycheckout_heared').value=="Others"){
            $('easycheckout_other').setStyle({display:"inline"});
            if($('advice-validate-select-easycheckout_heared')){
               $('advice-validate-select-easycheckout_heared').setStyle({display:"none"});
               $('easycheckout_heared').removeClassName('validation-failed');
           }
       }else{
           $('easycheckout_other').setStyle({display:"none"});
           if($('advice-required-entry-easycheckout_other')){
               $('advice-required-entry-easycheckout_other').setStyle({display:"none"});
               $('easycheckout_other').removeClassName('validation-failed');
               
           }
       }
    });
      //]]>
</script>